### ISSUE TITLE
Texture images

### ISSUE THREAD

**Issue by dermotbalson** [loopspace/Codea-Shapes#1]
I think users should either provide a single image, or a 6x1 image for cubes, or whatever is needed for other shapes.

I don't think requiring an 8x1 image solves the fractional problem, because an image of 91 pixels isn't divisible by 8. 

Also, if you have set up 6 same-sized pictures, the total width will be divisible by 6 anyway.

**Comment by loopspace** [comment]
The problem that I was trying to avoid with using an `8x1` image was that due to floating point arithmetic, `6 * 1/6` is not quite `1` but `8 * 1/8` is exactly `1`.  So if your image width is a multiple of `8`, which it will be if it is created by taking an image and tiling it `8` times, then `1/8`th of it is guaranteed to be what it is expected to be.  However, even if your image is a multiple of `6`, you are relying on rounding to ensure that `1/6`th of it is what you want it to be, and not a pixel either way.  Rounding errors may be compounded by the fact that the initial assignment is in Codea, which is 64bit, and the texture division is done by OpenGL which is (I believe) 32bit.

But maybe I'm worrying unnecessarily here.  I'll change it to `1/6`th.

**Comment by dermotbalson** [comment]
Can we make it that the user either provides 6x1 or just 1x1?

If 1x1 is provided, it can be copied to 6x1 to avoid changing the code, but you do have to watch out for Codea's image size limits in doing so. Some of my stored images exceed 2048 pixels when copied 6 times, producing a black screen result. Maybe the answer is to restrict width to a maximum of 250 when copying.

But as I said, let's not go overboard on this. Once the image is sorted, I think we just need a couple of good demo images, and some help notes, and we're done.

**Comment by loopspace** [comment]
When you say `6x1` or `1x1` it sounds as though you want Codea to automatically detect the size of the image.

One problem with that is that the cube might not be a regular cube so the sides might not be the same sizes so detecting whether the sides match is not a reliable test.  It would be better for the user to provide a switch to say "Use this image on each side".  In fact, if it was to be the same image on each side then we wouldn't need to tile the image six times but simply adjust the texture coordinates.

**Comment by dermotbalson** [comment]
I'm ok with a separate switch

**Comment by loopspace** [comment]
I've put in a switch and it works fine; it'll be in the next update.
